export const DashboardTableData = [
  {
    sno: 1,
    clinicName: "Mayo Clinic",
    ehrName: "EPIC",
    ehrLogo: "epic.png",
    abbottAppName: "HF Cloud",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Success",
    dateTime: "06-01-2025 18:30:25",
    successCount: 3,
    errorCount: 3,
    inProgressCount: 3,
    comments: "Successful",
  },
  {
    sno: 2,
    clinicName: "Cleveland Clinic",
    ehrName: "Cerner",
    ehrLogo: "cerner.png",
    abbottAppName: "DRX",
    middlewareName: "Corepoint",
    middleWareLogo: "corepoint.png",
    status: "Success",
    dateTime: "05-01-2025 18:30:25",
    successCount: 3,
    errorCount: 6,
    inProgressCount: 3,
    comments: "Successful",
  },
  {
    sno: 3,
    clinicName: "NYU Langone",
    ehrName: "EPIC",
    ehrLogo: "epic.png",
    abbottAppName: "NM",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Failure",
    dateTime: "04-01-2025 18:30:25",
    successCount: 4,
    errorCount: 2,
    inProgressCount: 6,
    comments: "App Error",
  },
  {
    sno: 4,
    clinicName: "Johns Hopkins",
    ehrName: "MEDITECH",
    ehrLogo: "meditech.png",
    abbottAppName: "CRM",
    middlewareName: "Corepoint",
    middleWareLogo: "corepoint.png",
    status: "Failure",
    dateTime: "03-01-2025 18:30:25",
    successCount: 43,
    errorCount: 23,
    inProgressCount: 3,
    comments: "App Error",
  },
  {
    sno: 5,
    clinicName: "Stanford Health",
    ehrName: "Cerner",
    ehrLogo: "cerner.png",
    abbottAppName: "ADC",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Success",
    dateTime: "02-01-2025 18:30:25",
    successCount: 43,
    errorCount: 23,
    inProgressCount: 43,
    comments: "Successful",
  },
  {
    sno: 6,
    clinicName: "Duke University",
    ehrName: "MEDITECH",
    ehrLogo: "meditech.png",
    abbottAppName: "CRM",
    middlewareName: "Corepoint",
    middleWareLogo: "corepoint.png",
    status: "Warning",
    dateTime: "01-01-2025 18:30:25",
    successCount: 3,
    errorCount: 3,
    inProgressCount: 3,
    comments: "Network Warning",
  },
  {
    sno: 7,
    clinicName: "Mount Sinai Hospital",
    ehrName: "EPIC",
    ehrLogo: "epic.png",
    abbottAppName: "HF Cloud",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Warning",
    dateTime: "31-12-2024 18:30:25",
    successCount: 13,
    errorCount: 5,
    inProgressCount: 3,
    comments: "Network Warning",
  },
  {
    sno: 8,
    clinicName: "UCSF Health",
    ehrName: "MEDITECH",
    ehrLogo: "meditech.png",
    abbottAppName: "ADC",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Success",
    dateTime: "30-12-2024 18:30:25",
    successCount: 3,
    errorCount: 8,
    inProgressCount: 3,
    comments: "Successful",
  },
  {
    sno: 9,
    clinicName: "Rush University",
    ehrName: "Cerner",
    ehrLogo: "cerner.png",
    abbottAppName: "EP",
    middlewareName: "Rhapsody",
    middleWareLogo: "rhapsody.webp",
    status: "Success",
    dateTime: "29-12-2024 18:30:25",
    successCount: 3,
    errorCount: 4,
    inProgressCount: 3,
    comments: "Successful",
  },
];
